<?php 
echo $this->doctype(); 
?>
<html lang="en">
    <head>
        <title>NEL - LATINO (Empresa dedicada al comercio electrónico)</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; ISO-8859-1">
        <meta name="DC.Language" scheme="RFC1766" content="Spanish">
        <meta name="AUTHOR" content="NEL SIGIFREDO MACÍAS INTRIAGO">
        <meta name="REPLY-TO" content="chavomacias12@gmail.com">
        <link rev="made" href="mailto:chavomacias12@gmail.com">
        <meta property="og:image" content="<?php echo $this->basePath(); ?>/public/images/otras/vistaprevia.jpg"/>
        <meta name="DESCRIPTION" content="Empresa dedicada al comercio electrónico, crea una cuenta empieza a vender en línea, puedes comprar en línea productos con confianza, porque NEL - LATINO trabaja con tiendas registradas en el sri.">
        <meta name="KEYWORDS" content="comercio electrónico,tienda en línea,tienda,productos,telefonos,tecnología,ropa,blusas vestidos,repuestos,perfumes,instrumentos,guitarra,violin,juegos,pantalon,camisa,camiseta,zapatos,zapatillas,sandalias,monos,enterizos,comida">
        <meta name="Resource-type" content="Document">
        <meta name="DateCreated" content="Mon, 5 March 2018 00:00:00 GMT-8">
        <meta name="Revisit-after" content="10 days">
        <meta name="robots" content="ALL">  
        <link rel="icon" type="image/png" href="<?php echo $this->basePath();?>/public/images/otras/favico.png" />
        <!-- Le styles -->
        <?php echo $this->headLink()
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/public/dist/css/AdminLTE.min.css')
                ->prependStylesheet($this->basePath() . '/public/dist/css/skins/_all-skins.min.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/iCheck/flat/blue.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/morris/morris.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/jvectormap/jquery-jvectormap-1.2.2.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/datepicker/datepicker3.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/daterangepicker/daterangepicker.css')
                ->prependStylesheet($this->basePath() . '/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                ->prependStylesheet($this->basePath() . '/public/bootstrap/css/bootstrap.min.css');
                ?>
        

                        <?php echo $this->headScript()  
                ->prependFile($this->basePath() . '/public/js/jquery.form.js')   
                ->prependFile($this->basePath() . '/public/dist/js/demo.js') 
                ->prependFile($this->basePath() . '/public/dist/js/app.min.js') 
                ->prependFile($this->basePath() . '/public/plugins/fastclick/fastclick.js') 
                ->prependFile($this->basePath() . '/public/plugins/slimScroll/jquery.slimscroll.min.js') 
                ->prependFile($this->basePath() . '/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') 
                ->prependFile($this->basePath() . '/public/plugins/datepicker/bootstrap-datepicker.js') 
                ->prependFile($this->basePath() . '/public/plugins/daterangepicker/daterangepicker.js')                
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js')                   
                ->prependFile($this->basePath() . '/public/plugins/knob/jquery.knob.js')   
                ->prependFile($this->basePath() . '/public/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')   
                ->prependFile($this->basePath() . '/public/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') 
                ->prependFile($this->basePath() . '/public/plugins/sparkline/jquery.sparkline.min.js')  
                ->prependFile($this->basePath() . '/public/plugins/morris/morris.min.js') 
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')   
                ->prependFile($this->basePath() . '/public/bootstrap/js/bootstrap.min.js')   
                ->prependFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js')  
                ->prependFile($this->basePath() . '/public/plugins/jQuery/jquery-2.2.3.min.js'); ?>
    </head>
    
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <header class="main-header">
                <a style="position: fixed;" href="<?php echo $this->basePath();?>/index/index" class="logo">
                    <span class="logo-mini"><b>N</b>L</span>
                    <span class="logo-lg"><b>NEL-</b>LATINO</span>
                </a>
                <nav class="navbar navbar-fixed-top">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                      <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav" id="contenedorMenuCliente">

                        </ul>
                    </div>
                </nav>
            </header>
            <style type="text/css">
                .stuck {
                   position: fixed;
                    top: 10px;
                    left: 10px;
                    bottom: 10px;
                    overflow-y: auto;
                }
            </style>
            <aside class="main-sidebar stuck">
                <section class="sidebar">
                    <div class="">
                        <div class="">
                            <img style="width: 90%;" src="">
                        </div>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="header">MENÚ</li>
                        <li>
                            <a href="<?php echo $this->basePath();?>/index/index" style="cursor: pointer; color: white;" ><i class="fa fa-share"></i><span>REGITRO VOTOS</span></a>
                        </li>
                         <li>
                            <a href="<?php echo $this->basePath();?>/index/resultados" style="cursor: pointer; color: white;" ><i class="fa fa-share"></i><span>RESULTADOS</span></a>
                        </li>
                    </ul>
                </section>
            </aside>
            <?php echo $this->content; ?>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Versión</b> 2.0.0
                </div>
                <strong>Empresa dedicada al comercio electrónico.</strong>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>          
</html>
